### ISSUE TITLE
MTGO log parser

### ISSUE THREAD

**Issue by ValentinPerret** [kazooki117/mtg-data-analysis#6]
Use code pushed in the branch `importer` as a base for a parser of MTGO data. 

# Definition

**Parser input:** MTGO draft logs
**Parser output:** Dataframe following data structure described in #1 

# Constraints

- Should work with the data provided by Kazooki website
- Should work with direct extract of the data from MTGO

**Comment by rconroy293** [comment]
Completed in https://github.com/kazooki117/mtg-data-analysis/pull/11
